### ISSUE TITLE
Official releases

### ISSUE THREAD

**Issue by SnarkBoojum** [davepacheco/node-getopt#5]
Hi,

when you bump the version up, could you also tag the commit, that will make sure github makes a release tarball from it and Debian will also detect the new version and notify me so to update the package.

Thanks!

**Comment by davepacheco** [comment]
I will do this for future releases.  (I've been adopting this for all of my repos as I make new releases, but I don't believe this package has had a release for a while.)

There's a Debian package?

**Comment by SnarkBoojum** [comment]
Yes, there [is](https://tracker.debian.org/pkg/node-posix-getopt), and I'm the culprit.

Thanks!
